-- Las contraseñas son las mismas que el nombre de usuario, pero encriptadas con BCrypt.
insert into users (id,
                   name,
                   last_name,
                   phone_number,
                   email,
                   username,
                   password,
                   enabled,
                   account_non_expired,
                   account_non_locked,
                   credentials_non_expired)

-- Administrador del sistema (1)
values (1,
        'Admin',
        'Admin',
        3207108160,
        'admin@gmail.com',
        'admin',
        '$2a$12$xT9mj6/iXPRMxBBVahsYSOmgUIGyTaKOdNvnHSj/ILOlnkee.UODK',
        true,
        true,
        true,
        true),

       -- Administradores de clubes (5)
       (2,
        'Alexa',
        'Rodríguez Hernández',
        3156765546,
        'alexarh23@gmail.com',
        'alexarh23',
        '$2a$12$sukFVnISeTUQfoC8dSq3o.B7Dx/bNbaB8o0RG80HzZGX2aGoBFC2e',
        true,
        true,
        true,
        true),
       (3,
        'Jane',
        'Doe',
        3125467789,
        'janedoe23@gmail.com',
        'janedoe23',
        '$2a$12$zP1ULlAY5njAOe/PhuwDMOsqVsld/VVY.xQP7KpFK3MZNUpHiZOnS',
        true,
        true,
        true,
        true),
       (4,
        'John',
        'Smith',
        3143456789,
        'johnsmith13@gmail.com',
        'johnsmith13',
        '$2a$12$Mo9UIrlHjSCgqO25LoErbOUb9rF5L7ROsbbxGOP/vxd07ovTFx7yC',
        true,
        true,
        true,
        true),
       (5,
        'Emily',
        'Johnson',
        3135551234,
        'emilyjohnson32@gmail.com',
        'emilyjohnson32',
        '$2a$12$HRxXsOwG7gvJE4d5GO6oc.0b.k4DZbASzH5dNdf2syVNhs6JPxP/G',
        true,
        true,
        true,
        true),
       (6,
        'Carlos',
        'Gómez',
        3101234567,
        'carlosgomez@gmail.com',
        'carlosgomez',
        '$2a$12$t9HxJCj/mlUcR4ADzweHAOxYwBqeHL/0QXejDUyAY5hvZiyylWT42',
        true,
        true,
        true,
        true),

       -- Entrenadores (5)
       (7,
        'María',
        'Pérez',
        3112345678,
        'mariaperez@gmail.com',
        'mariaperez',
        '$2a$12$gboLs3R3sPceHsMiu/z2KuEUE2.TGr4Rzoi16zdn1Viq6dB5ds9Oq',
        true,
        true,
        true,
        true),
       (8,
        'Luis',
        'Martínez',
        3123456789,
        'luismartinez@gmail.com',
        'luismartinez',
        '$2a$12$uY3w8n9LPi0QcZX5WVA0LuYy6xJaYuLaIjUZ3l4hs2j3de0595aA.',
        true,
        true,
        true,
        true),
       (9,
        'Ana',
        'López',
        3134567890,
        'analopez@gmail.com',
        'analopez',
        '$2a$12$ovK99s5AM9Lta04X2HCSPOJDh/DbC0Fl6cOQDz6atg6uxc.mm9TKy',
        true,
        true,
        true,
        true),
       (10,
        'Jorge',
        'Hernández',
        3145678901,
        'jorgehernandez@gmail.com',
        'jorgehernandez',
        '$2a$12$1Z5y7DT2e1.t5a9lyQfeiOxRKUAptHbOKCF.jSMS90Y3um4ZQ18ya',
        true,
        true,
        true,
        true),
       (11,
        'Sofía',
        'Ramírez',
        3156789012,
        'sofiaramirez@gmail.com',
        'sofiaramirez',
        '$2a$12$9u75clDPiMUQ0lX.0mPhWuMfwKMf/PMOT0OnNhn9b542oBoyGznIG',
        true,
        true,
        true,
        true),

       -- Jugadores (15)
       (12,
        'Diego',
        'Torres',
        3167890123,
        'diegotorres@gmail.com',
        'diegotorres',
        '$2a$12$jE8QgClI20/5YOJJXJAI3eLGLciCzO8kMNjKrTpDi0OcD02P1fuxi',
        true,
        true,
        true,
        true),
       (13,
        'Laura',
        'Vargas',
        3178901234,
        'lauravargas@gmail.com',
        'lauravargas',
        '$2a$12$6.FSg/k.vRcaT1RrndM0WODZzz/D9./3hA7L0HAh9zcdHftb2udIO',
        true,
        true,
        true,
        true),
       (14,
        'Andrés',
        'Castro',
        3189012345,
        'andrescastro@gmail.com',
        'andrescastro',
        '$2a$12$1qrCeiEg7TPwFvPnBzSLn.ufvZfQWPDJDhbdHD1dw2aJHX5k5U.me',
        true,
        true,
        true,
        true),
       (15,
        'Paula',
        'Morales',
        3190123456,
        'paulamorales@gmail.com',
        'paulamorales',
        '$2a$12$RgN4BgevHegbBR8PF/GQiuGZma8EkQesH7NBJEKmgwdEVpTkKk5dK',
        true,
        true,
        true,
        true),
       (16,
        'Ricardo',
        'Rojas',
        3201234567,
        'ricardorojas@gmail.com',
        'ricardorojas',
        '$2a$12$FWkEkLpskzdySS3cKRC30e2F5leedbXu9rkUPsOvGSZoWe.AOcP2.',
        true,
        true,
        true,
        true),
       (17,
        'Valeria',
        'Cruz',
        3212345678,
        'valeriacruz@gmail.com',
        'valeriacruz',
        '$2a$12$u440miFxH8CEc6jteBYYBOV/fZeCJO6W2k5o4vVl66bOwJ0dylyja',
        true,
        true,
        true,
        true),
       (18,
        'Fernando',
        'Mendoza',
        3223456789,
        'fernandomendoza@gmail.com',
        'fernandomendoza',
        '$2a$12$7kilkzszTdhL.A/H980nzOaH/v1J7jSFDLT93nwHTFSPpmSrFXY3q',
        true,
        true,
        true,
        true),
       (19,
        'Camila',
        'Ortiz',
        3234567890,
        'camilaortiz@gmail.com',
        'camilaortiz',
        '$2a$12$U7Bvwfe7R/mlLGHLuNHU6.1oPjQ9FVQHkB3GgUwxsPL6KgEXkOUkG',
        true,
        true,
        true,
        true),
       (20,
        'Sebastián',
        'Reyes',
        3245678901,
        'sebastianreyes@gmail.com',
        'sebastianreyes',
        '$2a$12$rPwgshdH9fXc8n.Q4CzwK.cjUUyjLk8ZitA603dEaHlgB8ysMqh92',
        true,
        true,
        true,
        true),
       (21,
        'Isabella',
        'Silva',
        3256789012,
        'isabellasilva@gmail.com',
        'isabellasilva',
        '$2a$12$fVTkJOW2l5.nvDPMyt3l/OZ2fndEgEmY79/ufLPLpZdCvCj3ha2iq',
        true,
        true,
        true,
        true),
       (22,
        'Mateo',
        'García',
        3267890123,
        'mateogarcia@gmail.com',
        'mateogarcia',
        '$2a$12$d3PQ8aLP14o84fUUa2qesO/bL4JVbv3oUl9g/Ltp8oFuZTX.P0Bbe',
        true,
        true,
        true,
        true),
       (23,
        'Daniela',
        'Navarro',
        3278901234,
        'danielanavarro@gmail.com',
        'danielanavarro',
        '$2a$12$epD8Bm1COET/a4ph8hqjj.fErLjsB2Lj4s4L.LvTnUrhM.tPyQE5W',
        true,
        true,
        true,
        true),
       (24,
        'Santiago',
        'Paredes',
        3289012345,
        'santiagoparedes@gmail.com',
        'santiagoparedes',
        '$2a$12$P64xH52xFRSGsqJBrZhu9uZlGS366Zudy96eM4CPMzqmNHyQXFeom',
        true,
        true,
        true,
        true),
       (25,
        'Lucía',
        'Peña',
        3290123456,
        'luciapeña@gmail.com',
        'luciapeña',
        '$2a$12$b7LyF4LTtdYJo1o.62pU0O8zxB6Nf57tE4253xAzORnBzMkhBw13W',
        true, true,
        true,
        true),
       (26,
        'Alejandro',
        'Salazar',
        3301234567,
        'alejandrosalazar@gmail.com',
        'alejandrosalazar',
        '$2a$12$zSFDek/.sK5872Ji3H6NqOuNIY2AzPlSVtQysm7N3jiLuUBBD04PO',
        true,
        true,
        true,
        true);

insert into club_administrators(id)
values (2),
       (3),
       (4),
       (5),
       (6);

insert into coaches(id)
values (7),
       (8),
       (9),
       (10),
       (11);

insert into players(id)
values (12),
       (13),
       (14),
       (15),
       (16),
       (17),
       (18),
       (19),
       (20),
       (21),
       (22),
       (23),
       (24),
       (25),
       (26);

insert into roles (name)
values ('ROLE_ADMIN'),
       ('ROLE_CLUB_ADMIN'),
       ('ROLE_COACH'),
       ('ROLE_PLAYER'),
       ('ROLE_USER');

insert into authorities (name)
values ('AUTHORITY_VIEW_ALL'),
       ('AUTHORITY_MANAGE_MEMBERS'),
       ('AUTHORITY_MANAGE_CLUB'),
       ('AUTHORITY_VIEW_MEMBERS'),
       ('AUTHORITY_MANAGE_TRAINING'),
       ('AUTHORITY_VIEW_PROFILE'),
       ('AUTHORITY_VIEW_TOURNAMENTS'),
       ('AUTHORITY_READ'),
       ('AUTHORITY_WRITE');

insert into users_roles (user_id, role_id)
-- Administrador del sistema
values (1, 1),

       -- Administradores de clubes
       (2, 2),
       (3, 2),
       (4, 2),
       (5, 2),
       (6, 2),

       -- Entrenadores
       (7, 3),
       (8, 3),
       (9, 3),
       (10, 3),
       (11, 3),

       -- Jugadores
       (12, 4),
       (13, 4),
       (14, 4),
       (15, 4),
       (16, 4),
       (17, 4),
       (18, 4),
       (19, 4),
       (20, 4),
       (21, 4),
       (22, 4),
       (23, 4),
       (24, 4),
       (25, 4),
       (26, 4),

       -- Usuarios
       (1, 5),
       (2, 5),
       (3, 5),
       (4, 5),
       (5, 5),
       (6, 5),
       (7, 5),
       (8, 5),
       (9, 5),
       (10, 5),
       (11, 5),
       (12, 5),
       (13, 5),
       (14, 5),
       (15, 5),
       (16, 5),
       (17, 5),
       (18, 5),
       (19, 5),
       (20, 5),
       (21, 5),
       (22, 5),
       (23, 5),
       (24, 5),
       (25, 5),
       (26, 5);

insert into roles_authorities (role_id, authority_id)
values (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 9),

       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (2, 6),
       (2, 7),
       (2, 9),

       (3, 5),
       (3, 6),
       (3, 7),

       (4, 6),
       (4, 7),

       (5, 8);